# Generated by Django 2.2 on 2020-05-22 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0004_auto_20200505_1954'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Blog', 'verbose_name_plural': 'Unser Blog'},
        ),
        migrations.AlterModelOptions(
            name='sidewidget',
            options={'verbose_name': 'Side widgets', 'verbose_name_plural': 'Side widgets (Weiß nicht auf Deutsch hahaha)'},
        ),
    ]
